name = "employment-survey-api-prod"
main = "src/worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# 本地开发配置
[dev]
port = 8787

# 环境变量
[vars]
ENVIRONMENT = "production"
JWT_SECRET = "your-jwt-secret-key-change-in-production"
CORS_ORIGIN = "*"
R2_BUCKET_NAME = "employment-survey-storage"
GOOGLE_CLIENT_SECRET = "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"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "college-employment-survey"
database_id = "25eee5bd-9aee-439a-8723-c73bf5f4f3d9"

# R2 存储配置
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "employment-survey-storage"

# AI 配置 - Cloudflare Workers AI with Gateway
[ai]
binding = "AI"
gateway_id = "chris-ai-01"

# Analytics Engine 配置
[[analytics_engine_datasets]]
binding = "ANALYTICS"

# 定时任务配置
[triggers]
crons = [
  "*/30 * * * *",   # 每30分钟：问卷2数据同步到静态表
  "0 2 * * *"       # 每天凌晨2点：数据库备份 + 清理旧备份
]

# 测试环境配置 - 问卷2集成测试
[env.test]
name = "employment-survey-api-test"
[env.test.vars]
ENVIRONMENT = "test"
JWT_SECRET = "test-jwt-secret-key-for-questionnaire2"
CORS_ORIGIN = "*"
R2_BUCKET_NAME = "employment-survey-storage-test"
GOOGLE_CLIENT_SECRET = "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"

# 测试环境使用相同的数据库，但会添加问卷2专用表
[[env.test.d1_databases]]
binding = "DB"
database_name = "college-employment-survey"
database_id = "25eee5bd-9aee-439a-8723-c73bf5f4f3d9"

# R2存储桶暂时禁用，避免部署错误
# [[env.test.r2_buckets]]
# binding = "R2_BUCKET"
# bucket_name = "employment-survey-storage-test"

[env.test.ai]
binding = "AI"
gateway_id = "chris-ai-01"

[[env.test.analytics_engine_datasets]]
binding = "ANALYTICS"
