name = "employment-survey-api-prod"
main = "src/cloudflare-worker.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# 环境变量
[vars]
ENVIRONMENT = "production"
JWT_SECRET = "your-jwt-secret-key-change-in-production"
CORS_ORIGIN = "*"
R2_BUCKET_NAME = "employment-survey-storage"
GOOGLE_CLIENT_SECRET = "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"

# D1 数据库配置
[[d1_databases]]
binding = "DB"
database_name = "college-employment-survey"
database_id = "25eee5bd-9aee-439a-8723-c73bf5f4f3d9"

# R2 存储配置
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "employment-survey-storage"

# 定时任务配置
[triggers]
crons = [
  "*/5 * * * *",    # 每5分钟执行一次统计缓存更新
  "0 8 * * *",      # 每天上午8点执行数据一致性检查
  "0 2 * * *"       # 每天凌晨2点执行数据质量监控
]
